apiVersion: 1

datasources:
  - name: Prometheus-HomeAutomation
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"

  - name: PostgreSQL-HomeAutomation
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    database: home_automation
    basicAuth: false
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: true
