apiVersion: 1

datasources:
  - name: InfluxDB-HomeAutomation
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    database: sensor-data
    basicAuth: false
    isDefault: true
    jsonData:
      version: Flux
      organization: home-automation
      defaultBucket: sensor-data
      tlsSkipVerify: true
    secureJsonData:
      token: home-automation-token
    editable: true

  - name: PostgreSQL-HomeAutomation
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    database: home_automation
    basicAuth: false
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: true
