global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Home Automation Go Backend
  - job_name: 'home-automation'
    static_configs:
      - targets: ['home-automation:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # MQTT Exporter (if using mqtt-exporter)
  - job_name: 'mqtt-exporter'
    static_configs:
      - targets: ['mqtt-exporter:9641']
    scrape_interval: 10s

  # Redis metrics (if using redis-exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
