blank_issues_enabled: false
contact_links:
  - name: Home Automation Discussions
    url: https://github.com/johnpr01/home-automation/discussions
    about: Please ask and answer questions here.
  - name: Security Issue
    url: https://github.com/johnpr01/home-automation/security/policy
    about: Please report security vulnerabilities here.
